g1_controller_node:
  ros__parameters:
    arm_joint_names:
      - left_shoulder_pitch
      - left_shoulder_roll
      - left_shoulder_yaw
      - left_elbow
      - left_wrist_roll
      - left_wrist_pitch
      - left_wrist_yaw
      - right_shoulder_pitch
      - right_shoulder_roll
      - right_shoulder_yaw
      - right_elbow
      - right_wrist_roll
      - right_wrist_pitch
      - right_wrist_yaw
      - waist_yaw
      - waist_roll
      - waist_pitch
