g1_controller_node:
  ros__parameters:
    joint_limit_names:
      - left_shoulder_pitch
      - left_shoulder_roll
      - left_shoulder_yaw
      - left_elbow_pitch
      - left_elbow_roll
      - right_shoulder_pitch
      - right_shoulder_roll
      - right_shoulder_yaw
      - right_elbow_pitch
      - right_elbow_roll
      - waist_yaw
      - waist_roll
      - waist_pitch
      - left_elbow
      - left_wrist_roll
      - left_wrist_pitch
      - left_wrist_yaw
      - right_elbow
      - right_wrist_roll
      - right_wrist_pitch
      - right_wrist_yaw
    joint_limit_min_positions:
      - -2.5
      - -2.0
      - -2.5
      - -2.0
      - -2.0
      - -2.5
      - -2.0
      - -2.5
      - -2.0
      - -2.0
      - -1.2
      - -1.2
      - -1.2
      - -2.0
      - -1.8
      - -1.8
      - -1.8
      - -2.0
      - -1.8
      - -1.8
      - -1.8
    joint_limit_max_positions:
      - 2.5
      - 2.0
      - 2.5
      - 2.0
      - 2.0
      - 2.5
      - 2.0
      - 2.5
      - 2.0
      - 2.0
      - 1.2
      - 1.2
      - 1.2
      - 2.0
      - 1.8
      - 1.8
      - 1.8
      - 2.0
      - 1.8
      - 1.8
      - 1.8
    joint_limit_max_velocities:
      - 1.5
      - 1.5
      - 1.5
      - 1.5
      - 1.5
      - 1.5
      - 1.5
      - 1.5
      - 1.5
      - 1.5
      - 1.0
      - 1.0
      - 1.0
      - 1.5
      - 2.0
      - 2.0
      - 2.0
      - 1.5
      - 2.0
      - 2.0
      - 2.0
